// N:M associations tables can be auto-generated by sequelize, or passed through a model (therefore not sure if this is needed here at all)

module.exports = function (sequelize, DataTypes) {
  var Fav = sequelize.define('Fav', {
    userEmail: {
      type: DataTypes.STRING,
      primaryKey: true,
      allowNull: false,
      validate: {
        len: [10]
      }
    },
    optionId: {
      type: DataTypes.INTEGER,
      allowNull: false,
      validate: {
        len: [1]
      }
    },
  });

  // User.belongsToMany(Option, { through: Fav });
  // Option.belongsToMany(User, { through: Fav });
  
  // user.addOption(option, { email: user_email, id: option_id, transaction: t });

  return Fav;
};



// var orm = require('../config/orm.js');

// var user_favs = {
//     all: function(cb) {
//         orm.all('user_favs', function(res) {
//           cb(res);
//         });
//       },
//       // The variables cols and vals are arrays.
//       create: function(cols, vals, cb) {
//         orm.create('user_favs', cols, vals, function(res) {
//           cb(res);
//         });
//       },
//       update: function(objColVals, condition, cb) {
//         orm.update('user_favs', objColVals, condition, function(res) {
//           cb(res);
//         });
//       },
//       delete: function(condition, cb) {
//         orm.delete('user_favs', condition, function(res) {
//           cb(res);
//         });
//       }
// };

// module.exports = user_favs;