// N:M associations tables can be auto-generated by sequelize, or passed through a model (therefore not sure if this is needed here at all)

module.exports = function (sequelize, DataTypes) {
  var Fav = sequelize.define('Fav', {
    userEmail: {
      type: DataTypes.STRING,
      primaryKey: true,
      allowNull: false,
      validate: {
        len: [10]
      }
    },
    optionId: {
      type: DataTypes.INTEGER,
      allowNull: false,
      validate: {
        len: [1]
      }
    },
  });

  // User.belongsToMany(Option, { through: Fav });
  // Option.belongsToMany(User, { through: Fav });
  
  // user.addOption(option, { email: user_email, id: option_id, transaction: t });

  return Fav;
};